import { SITE_CANONICAL_URL } from "@/lib/constants";
import { JsonLd, buildBreadcrumbList, type BreadcrumbItem } from "./JsonLd";
import {
  DEMOGRAPHIC_AUTHORS,
  derivePeptideRecs,
  type DemographicCluster,
  type DemographicPageData,
} from "@/data/demographic-pages";

/**
 * Emits all structured data for a demographic landing page:
 *   - BreadcrumbList   (sitelinks)
 *   - MedicalWebPage   (health-topic eligibility) — linked to root WebSite + Organization
 *   - Article          (article rich result) — linked to MedicalWebPage via mainEntity
 *   - FAQPage          (FAQ rich result)
 *   - ItemList         (ranked peptide list — surfaces in carousels)
 *
 * Entity graph: both Article and MedicalWebPage carry @id values and reference
 * each other (mainEntity / mainEntityOfPage). Publisher / isPartOf point at the
 * #organization and #website nodes declared once in app/layout.tsx.
 */

function specialtyForCluster(cluster: DemographicCluster): string {
  // schema.org MedicalSpecialty enumeration members — full URLs are the most
  // validator-friendly form (bare strings work but trip warnings in some tools).
  switch (cluster) {
    case "condition":
      return "https://schema.org/Endocrine";
    case "aesthetic":
      return "https://schema.org/Dermatologic";
    case "recovery":
      return "https://schema.org/PhysicalMedicine";
    case "mental-health":
      return "https://schema.org/Psychiatric";
    case "athlete":
    case "body-type":
      return "https://schema.org/SportsMedicine";
    case "life-stage":
      return "https://schema.org/ObstetricGynecologic";
    case "age-gender":
    case "goal":
    case "lifestyle":
    case "safety":
    default:
      return "https://schema.org/PreventiveMedicine";
  }
}

function aspectForCluster(cluster: DemographicCluster): string {
  switch (cluster) {
    case "condition":
    case "life-stage":
      return "TreatmentsHealthAspect";
    default:
      return "PreventionHealthAspect";
  }
}

function countWords(s: string | undefined | null): number {
  if (!s) return 0;
  return s.trim().split(/\s+/).filter(Boolean).length;
}

function estimateWordCount(page: DemographicPageData): number {
  let n = 0;
  n += countWords(page.tldr);
  n += countWords(page.heroSummary);
  n += countWords(page.seoDescription);
  for (const f of page.safetyFlags) n += countWords(f.label) + countWords(f.detail);
  for (const g of page.priorityGoals) n += countWords(g.framing);
  n += countWords(page.whyDifferent.intro);
  for (const p of page.whyDifferent.points) n += countWords(p);
  for (const sec of page.bodySections) {
    n += countWords(sec.title);
    for (const p of sec.paragraphs) n += countWords(p);
    if (sec.bullets) for (const b of sec.bullets) n += countWords(b);
  }
  for (const f of page.faqs) n += countWords(f.question) + countWords(f.answer);
  return n;
}

function articleSectionForCluster(cluster: DemographicCluster): string {
  switch (cluster) {
    case "age-gender":
      return "Age & Gender";
    case "life-stage":
      return "Life Stage";
    case "condition":
      return "Health Conditions";
    case "athlete":
      return "Athletes";
    case "aesthetic":
      return "Aesthetic";
    case "goal":
      return "Goals";
    case "lifestyle":
      return "Lifestyle";
    case "body-type":
      return "Body Type";
    case "recovery":
      return "Recovery";
    case "mental-health":
      return "Mental Health";
    case "safety":
      return "Safety";
    default:
      return "Peptides";
  }
}

export function DemographicJsonLd({
  page,
  breadcrumbs,
}: {
  page: DemographicPageData;
  breadcrumbs: BreadcrumbItem[];
}) {
  const canonical = `${SITE_CANONICAL_URL}${page.canonicalPath}`;
  const author = DEMOGRAPHIC_AUTHORS[page.authorId];

  const pageId = `${canonical}#webpage`;
  const articleId = `${canonical}#article`;
  const orgRef = { "@id": `${SITE_CANONICAL_URL}#organization` } as const;
  const websiteRef = { "@id": `${SITE_CANONICAL_URL}#website` } as const;

  const breadcrumbLd = buildBreadcrumbList(breadcrumbs);

  const authorLd = author
    ? {
        "@type": "Person",
        name: author.name,
        jobTitle: author.credentials,
        description: author.bio,
        url: `${SITE_CANONICAL_URL}/about`,
      }
    : undefined;

  // Article image: prefer per-page ogImage when set, otherwise fall back to the
  // per-template OG card generated by
  // src/app/blog/peptides-for/[slug]/opengraph-image.tsx (rendered by Next at
  // <canonical>/opengraph-image). Every Article entity must have a valid image
  // for article rich-result eligibility.
  const articleImage = page.ogImage
    ? page.ogImage.startsWith("http")
      ? page.ogImage
      : `${SITE_CANONICAL_URL}${page.ogImage}`
    : `${canonical}/opengraph-image`;

  const medicalWebPageLd = {
    "@context": "https://schema.org",
    "@type": "MedicalWebPage",
    "@id": pageId,
    url: canonical,
    name: page.h1,
    headline: page.h1,
    description: page.seoDescription,
    inLanguage: "en-US",
    datePublished: page.publishedAt,
    dateModified: page.updatedAt,
    lastReviewed: page.updatedAt,
    isPartOf: websiteRef,
    publisher: orgRef,
    audience: {
      "@type": "PeopleAudience",
      audienceType: page.audience,
    },
    medicalAudience: {
      "@type": "MedicalAudience",
      audienceType: "Patient",
    },
    specialty: specialtyForCluster(page.cluster),
    aspect: aspectForCluster(page.cluster),
    about: page.medicalCondition
      ? { "@type": "MedicalCondition", name: page.medicalCondition }
      : undefined,
    mainEntity: { "@id": articleId },
  };

  const recs = derivePeptideRecs(page);

  const articleLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "@id": articleId,
    headline: page.h1,
    description: page.seoDescription,
    datePublished: page.publishedAt,
    dateModified: page.updatedAt,
    inLanguage: "en-US",
    wordCount: estimateWordCount(page),
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": pageId,
      url: canonical,
    },
    image: [articleImage],
    author: authorLd,
    publisher: orgRef,
    articleSection: articleSectionForCluster(page.cluster),
    keywords: page.primaryKeyword,
    about: recs.length
      ? recs.map((r) => ({
          "@type": "Drug",
          name: r.peptide.name,
          alternateName: r.peptide.synonyms,
          url: `${SITE_CANONICAL_URL}/peptides/${r.peptide.slug}`,
        }))
      : undefined,
  };

  const faqLd = page.faqs.length
    ? {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: page.faqs.map((f) => ({
          "@type": "Question",
          name: f.question,
          acceptedAnswer: { "@type": "Answer", text: f.answer },
        })),
      }
    : null;

  const rankedListLd = recs.length
    ? {
        "@context": "https://schema.org",
        "@type": "ItemList",
        name: `${page.h1}: ranked compound recommendations`,
        itemListOrder: "https://schema.org/ItemListOrderDescending",
        numberOfItems: recs.length,
        itemListElement: recs.map((rec, i) => ({
          "@type": "ListItem",
          position: i + 1,
          item: {
            "@type": "Drug",
            name: rec.peptide.name,
            alternateName: rec.peptide.synonyms,
            description: rec.peptide.shortDescription,
            url: `${SITE_CANONICAL_URL}/peptides/${rec.peptide.slug}`,
          },
        })),
      }
    : null;

  return (
    <>
      <JsonLd data={breadcrumbLd} />
      <JsonLd data={medicalWebPageLd} />
      <JsonLd data={articleLd} />
      {faqLd && <JsonLd data={faqLd} />}
      {rankedListLd && <JsonLd data={rankedListLd} />}
    </>
  );
}
